services:
  postgres:
    image: postgres:latest
    container_name: postgres-keycloak-container
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  mongodb:
    image: mongo:latest
    container_name: mongo-keycloak-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: testMDB
    ports:
      - "27017:27017"  # Expose MongoDB on the default port
    volumes:
      - mongo_data:/data/db

  mongo_express:
    image: mongo-express:latest
    container_name: mongo-express-keycloak-container
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    ports:
      - "8081:8081"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-container
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
      KC_DB_URL_DATABASE: keycloakdb
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command: start-dev
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - keycloak-network

volumes:
  postgres_data:
  mongo_data:

networks:
  keycloak-network:
